#
debug: true

# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /
    
# LOGGING
logging:
  file: ./log/web.log
  #path: ./log
  
spring:
  application:
    name: spring-shiro
  # FreeMarker 
  freemarker:
    settings:
       template_exception_handler: com.xiangzi.freemarker.DefaultTemplateExceptionHandler
       auto_import: spring.ftl as spring
       
# Shiro
  
# Redis
redis:
  type: single
  host: 127.0.0.1
  port:  6379
  password: 123456
  database: 1
  timeout: 120000
  
  
